# Generated by Django 5.1.15 on 2026-05-30 03:31

import django.db.models.deletion
import django.utils.timezone
import sync.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('token', models.CharField(db_index=True, default=sync.models.generate_token, max_length=64, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(db_index=True, max_length=36, unique=True)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reference', models.CharField(blank=True, default='', max_length=80)),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('prix_unitaire', models.FloatField(default=0)),
                ('quantite_stock', models.FloatField(default=0)),
                ('seuil_alerte', models.FloatField(default=0)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.CharField(max_length=32)),
                ('updated_at', models.CharField(max_length=32)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sync.device')),
            ],
            options={
                'verbose_name': 'Produit',
            },
        ),
        migrations.CreateModel(
            name='RemoteUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(db_index=True, max_length=36, unique=True)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('identifiant', models.CharField(max_length=120)),
                ('nom_complet', models.CharField(max_length=200)),
                ('matricule', models.CharField(blank=True, default='', max_length=60)),
                ('telephone', models.CharField(blank=True, default='', max_length=40)),
                ('role', models.CharField(max_length=20)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.CharField(max_length=32)),
                ('updated_at', models.CharField(max_length=32)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sync.device')),
            ],
            options={
                'verbose_name': 'Utilisateur distant',
                'verbose_name_plural': 'Utilisateurs distants',
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(db_index=True, max_length=36, unique=True)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('matricule', models.CharField(db_index=True, max_length=80)),
                ('telephone', models.CharField(blank=True, default='', max_length=40)),
                ('product_id', models.IntegerField()),
                ('product_nom', models.CharField(max_length=200)),
                ('quantite', models.FloatField()),
                ('prix_unitaire', models.FloatField()),
                ('montant_total', models.FloatField()),
                ('solde_apres', models.FloatField()),
                ('agent_id', models.IntegerField(blank=True, null=True)),
                ('agent_nom', models.CharField(blank=True, default='', max_length=200)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.CharField(max_length=32)),
                ('deleted', models.BooleanField(default=False)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sync.device')),
            ],
            options={
                'verbose_name': 'Vente',
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(db_index=True, max_length=36, unique=True)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('product_id', models.IntegerField()),
                ('product_nom', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=10)),
                ('quantite', models.FloatField()),
                ('stock_apres', models.FloatField()),
                ('motif', models.CharField(blank=True, default='', max_length=255)),
                ('sale_id', models.IntegerField(blank=True, null=True)),
                ('agent_id', models.IntegerField(blank=True, null=True)),
                ('agent_nom', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.CharField(max_length=32)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sync.device')),
            ],
            options={
                'verbose_name': 'Mouvement de stock',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(db_index=True, max_length=36, unique=True)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('matricule', models.CharField(db_index=True, max_length=80)),
                ('telephone', models.CharField(blank=True, default='', max_length=40)),
                ('type', models.CharField(max_length=10)),
                ('montant', models.FloatField()),
                ('solde_apres', models.FloatField()),
                ('agent_id', models.IntegerField(blank=True, null=True)),
                ('agent_nom', models.CharField(blank=True, default='', max_length=200)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.CharField(max_length=32)),
                ('deleted', models.BooleanField(default=False)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sync.device')),
            ],
            options={
                'verbose_name': 'Transaction',
            },
        ),
    ]
