# Generated by Django 5.1.15 on 2026-05-30 04:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(db_index=True, max_length=36, unique=True)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('matricule', models.CharField(db_index=True, max_length=80)),
                ('nom', models.CharField(blank=True, default='', max_length=200)),
                ('telephone', models.CharField(blank=True, default='', max_length=40)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.CharField(max_length=32)),
                ('updated_at', models.CharField(max_length=32)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sync.device')),
            ],
            options={
                'verbose_name': 'Client',
            },
        ),
    ]
