# Generated by Django 5.1.15 on 2026-05-31 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0002_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='remoteuser',
            name='password_hash',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='remoteuser',
            name='identifiant',
            field=models.CharField(db_index=True, max_length=120),
        ),
    ]
