# Generated by Django 5.1.15 on 2026-05-31 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0003_remoteuser_password_hash_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='received_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='received_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='remoteuser',
            name='received_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='received_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='received_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='received_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
