# Generated by Django 5.1.15 on 2026-05-31 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0004_alter_client_received_at_alter_product_received_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='agent_uuid',
            field=models.CharField(blank=True, default='', max_length=36),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='agent_uuid',
            field=models.CharField(blank=True, default='', max_length=36),
        ),
        migrations.AddField(
            model_name='transaction',
            name='agent_uuid',
            field=models.CharField(blank=True, default='', max_length=36),
        ),
    ]
