# Generated by Django 5.1.15 on 2026-06-02 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0005_sale_agent_uuid_stockmovement_agent_uuid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(db_index=True, max_length=36, unique=True)),
                ('received_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('user_uuid', models.CharField(blank=True, db_index=True, default='', max_length=36)),
                ('user_identifiant', models.CharField(blank=True, default='', max_length=120)),
                ('action', models.CharField(db_index=True, max_length=80)),
                ('target_type', models.CharField(blank=True, default='', max_length=80)),
                ('target_id', models.CharField(blank=True, default='', max_length=80)),
                ('details', models.TextField(blank=True, default='')),
                ('created_at', models.CharField(db_index=True, max_length=32)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sync.device')),
            ],
            options={
                'verbose_name': "Entrée d'audit",
                'verbose_name_plural': "Entrées d'audit",
            },
        ),
    ]
