# Generated by Django 5.1.15 on 2026-06-02 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0006_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='product_uuid',
            field=models.CharField(blank=True, db_index=True, default='', max_length=36),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='product_uuid',
            field=models.CharField(blank=True, db_index=True, default='', max_length=36),
        ),
    ]
