# Generated by Django 5.2.1 on 2026-06-11 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0007_sale_product_uuid_stockmovement_product_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='remoteuser',
            name='can_delete',
            field=models.BooleanField(default=False),
        ),
    ]
