# Generated by Django 5.2.1 on 2026-07-07 09:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0008_remoteuser_can_delete'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockEntryRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_nom', models.CharField(max_length=200)),
                ('quantite', models.FloatField()),
                ('motif', models.CharField(blank=True, default='', max_length=255)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('valide', 'Validée'), ('rejete', 'Rejetée')], db_index=True, default='en_attente', max_length=12)),
                ('requested_by_identifiant', models.CharField(blank=True, default='', max_length=120)),
                ('requested_by_nom', models.CharField(blank=True, default='', max_length=200)),
                ('requested_by_uuid', models.CharField(blank=True, default='', max_length=36)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('validated_by_identifiant', models.CharField(blank=True, default='', max_length=120)),
                ('validated_by_nom', models.CharField(blank=True, default='', max_length=200)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('decision_motif', models.CharField(blank=True, default='', max_length=255)),
                ('resulting_movement_uuid', models.CharField(blank=True, default='', max_length=36)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry_requests', to='sync.product')),
            ],
            options={
                'verbose_name': "Demande d'entrée de stock",
                'verbose_name_plural': "Demandes d'entrée de stock",
                'ordering': ['-created_at'],
            },
        ),
    ]
