# Generated by Django 5.2.1 on 2026-07-08 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0009_stockentryrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockentryrequest',
            name='kind',
            field=models.CharField(choices=[('entree', 'Entrée sur produit existant'), ('nouveau_produit', "Création d'un nouveau produit")], db_index=True, default='entree', max_length=16),
        ),
        migrations.AddField(
            model_name='stockentryrequest',
            name='new_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='stockentryrequest',
            name='new_prix_unitaire',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='stockentryrequest',
            name='new_reference',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='stockentryrequest',
            name='new_seuil_alerte',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='stockentryrequest',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entry_requests', to='sync.product'),
        ),
    ]
