# Generated by Django 5.1.15 on 2026-09-16 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0016_reconciliation_snapshot_chunks'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='mode_paiement',
            field=models.CharField(default='compte', max_length=20),
        ),
        migrations.CreateModel(
            name='CashEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(db_index=True, max_length=36, unique=True)),
                ('received_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('date', models.CharField(db_index=True, max_length=32)),
                ('libelle', models.CharField(max_length=255)),
                ('entree', models.FloatField(default=0)),
                ('sortie', models.FloatField(default=0)),
                ('source', models.CharField(default='manuel', max_length=20)),
                ('sale_uuid', models.CharField(blank=True, db_index=True, default='', max_length=36)),
                ('agent_id', models.IntegerField(blank=True, null=True)),
                ('agent_uuid', models.CharField(blank=True, default='', max_length=36)),
                ('agent_nom', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.CharField(max_length=32)),
                ('deleted', models.BooleanField(default=False)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sync.device')),
            ],
            options={
                'verbose_name': 'Écriture de caisse',
            },
        ),
    ]
