# Generated by Django 5.1.15 on 2026-09-16 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0017_sale_mode_paiement_cashentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='suivi_stock',
            field=models.BooleanField(default=True),
        ),
    ]
