from django.urls import path

from web import views

app_name = "web"

urlpatterns = [
    path("login/", views.login_view, name="login"),
    path("logout/", views.logout_view, name="logout"),
    path("", views.dashboard, name="dashboard"),
    path("api/tableau-de-bord/", views.dashboard_stats_api, name="dashboard_stats_api"),
    path("api/synchroniser/", views.sync_now, name="sync_now"),
    path("api/produits/recherche/", views.product_search_api, name="product_search_api"),
    path("transactions/", views.transactions, name="transactions"),
    path("transactions/<int:pk>/supprimer/", views.transaction_delete, name="transaction_delete"),
    path("transactions/<int:pk>/restaurer/", views.transaction_restore, name="transaction_restore"),
    path("ventes/<int:pk>/supprimer/", views.sale_delete, name="sale_delete"),
    path("ventes/<int:pk>/restaurer/", views.sale_restore, name="sale_restore"),
    path("mouvements/<int:pk>/restaurer/", views.stock_movement_restore, name="stock_movement_restore"),
    path("produits/<int:pk>/restaurer/", views.product_restore, name="product_restore"),
    path("clients/<int:pk>/restaurer/", views.client_restore, name="client_restore"),
    path("corbeille/tout-supprimer/", views.trash_all_active_data, name="trash_all_active_data"),
    path("corbeille/", views.trash, name="trash"),
    path("transactions/depot/", views.deposit_new, name="deposit_new"),
    path("transactions/retrait/", views.withdrawal_new, name="withdrawal_new"),
    path("recu/ticket/", views.print_ticket, name="print_ticket"),
    path("transactions/retrait/facture/", views.withdrawal_invoice, name="withdrawal_invoice"),
    path("api/solde/", views.matricule_balance_api, name="matricule_balance_api"),
    path("ventes/nouvelle/", views.sale_new, name="sale_new"),
    path("ventes/", views.sales, name="sales"),
    path("produits/", views.products, name="products"),
    path("produits/nouveau/", views.product_new, name="product_new"),
    path("produits/demande-nouveau/", views.product_request_new, name="product_request_new"),
    path("produits/<int:pk>/modifier/", views.product_edit, name="product_edit"),
    path("produits/<int:pk>/basculer/", views.product_toggle, name="product_toggle"),
    path("produits/<int:pk>/stock/", views.stock_adjust, name="stock_adjust"),
    path("produits/<int:pk>/demande-entree/", views.stock_entry_request, name="stock_entry_request"),
    path("stock/validations/", views.stock_validations, name="stock_validations"),
    path("api/stock-a-valider/", views.pending_stock_api, name="pending_stock_api"),
    path("stock/validations/<int:pk>/valider/", views.stock_request_validate, name="stock_request_validate"),
    path("stock/validations/<int:pk>/rejeter/", views.stock_request_reject, name="stock_request_reject"),
    path("inventaire/", views.inventory, name="inventory"),
    path("mouvements/", views.stock_movements, name="stock_movements"),
    path("clients/", views.clients, name="clients"),
    path("clients/nouveau/", views.client_new, name="client_new"),
    path("clients/<int:pk>/modifier/", views.client_edit, name="client_edit"),
    path("clients/<int:pk>/basculer/", views.client_toggle, name="client_toggle"),
    path("postes/", views.devices_list, name="devices"),
    path("utilisateurs/", views.users_list, name="users"),
    path("utilisateurs/nouveau/", views.user_new, name="user_new"),
    path("utilisateurs/<int:pk>/modifier/", views.user_edit, name="user_edit"),
    path("utilisateurs/<int:pk>/basculer/", views.user_toggle, name="user_toggle"),
    path("journal/", views.audit_journal, name="journal"),
    path("rapports/", views.reports_view, name="reports"),
    path("quitter/", views.quit_app, name="quit_app"),
]
